name: jwtnest
services:
  postgres:
    container_name: jwtnest-postgres-db
    image: bitnami/postgresql:latest
    env_file:
      - ./.env
    ports:
      - 5435:5432
    
volumes:
  postgres_data:
    driver: local